In [1]:
import tensorflow as tf
from tensorflow.keras import models,layers,optimizers,utils
import numpy as np
import matplotlib as plt
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [5]:
df = pd.read_csv("/content/drive/MyDrive/ionosphere_data.csv")

In [6]:
df.head()

   feature1  feature2  feature3  ...  feature33  feature34  label
0         1         0   0.99539  ...    0.18641   -0.45300      g
1         1         0   1.00000  ...   -0.13738   -0.02447      b
2         1         0   1.00000  ...    0.56045   -0.38238      g
3         1         0   1.00000  ...   -0.32382    1.00000      b
4         1         0   1.00000  ...   -0.04608   -0.65697      g

[5 rows x 35 columns]

In [20]:
df.shape

(351, 35)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   feature1   351 non-null    int64
 1   feature2   351 non-null    int64
 2   feature3   351 non-null    float64
 3   feature4   351 non-null    float64
 4   feature5   351 non-null    float64
 5   feature6   351 non-null    float64
 6   feature7   351 non-null    float64
 7   feature8   351 non-null    float64
 8   feature9   351 non-null    float64
 9   feature10  351 non-null    float64
 10  feature11  351 non-null    float64
 11  feature12  351 non-null    float64
 12  feature13  351 non-null    float64
 13  feature14  351 non-null    float64
 14  feature15  351 non-null    float64
 15  feature16  351 non-null    float64
 16  feature17  351 non-null    float64
 17  feature18  351 non-null    float64
 18  feature19  351 non-null    float64
 19  feature20  351 non-null    float64
 20  feature21  351 non-null    float64
 21  feature22  351 non-null    float64
 22  feature23  351 non-null    float64
 23  feature24  351 non-null    float64
 24  feature25  351 non-null    float64
 25  feature26  351 non-null    float64
 26  feature27  351 non-null    float64
 27  feature28  351 non-null    float64
 28  feature29  351 non-null    float64
 29  feature30  351 non-null    float64
 30  feature31  351 non-null    float64
 31  feature32  351 non-null    float64
 32  feature33  351 non-null    float64
 33  feature34  351 non-null    float64
 34  label      351 non-null    object
dtypes: float64(32), int64(2), object(1)
memory usage: 96.1+ KB

In [8]:
df.isnull().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [16]:
from sklearn.utils import shuffle

df = shuffle(df)

In [18]:
df.reset_index(inplace=True, drop=True)

In [19]:
df.head()

   feature1  feature2  feature3  ...  feature33  feature34  label
0         1         0   0.62121  ...    0.17045   -0.41667      b
1         1         0   1.00000  ...    0.54252    0.50903      g
2         1         0   1.00000  ...    0.06990    0.71444      g
3         1         0   0.76046  ...    0.63887    0.01525      g
4         1         0  -0.00641  ...    0.00000    0.00000      b

[5 rows x 35 columns]

In [21]:
df

     feature1  feature2  feature3  ...  feature33  feature34  label
0           1         0   0.62121  ...    0.17045   -0.41667      b
1           1         0   1.00000  ...    0.54252    0.50903      g
2           1         0   1.00000  ...    0.06990    0.71444      g
3           1         0   0.76046  ...    0.63887    0.01525      g
4           1         0  -0.00641  ...    0.00000    0.00000      b
..        ...       ...       ...  ...        ...        ...    ...
346         1         0   0.97588  ...   -0.13832   -0.80975      g
347         1         0   0.84710  ...    0.85764   -0.06151      g
348         1         0   0.98182  ...    0.58840    0.17077      g
349         1         0   1.00000  ...    1.00000   -0.18826      b
350         1         0   0.88103  ...    0.91747   -0.16827      g

[351 rows x 35 columns]

In [12]:
df.shape

(351, 35)

In [32]:
train_data = df.iloc[0:210,0:34]
train_targets = df.iloc[0:210, 34]

test_data = df.iloc[210:, 0:-1]
test_targets = df.iloc[210:, -1]

In [36]:
#train_data
#train_targets
#test_data
#test_targets

210    g
211    b
212    g
213    g
214    g
      ..
346    g
347    b
348    g
349    b
350    b
Name: label, Length: 141, dtype: object

In [37]:
print(train_data.shape)
print(train_targets.shape)
print(test_data.shape)
print(test_targets.shape)

(210, 34)
(210,)
(141, 34)
(141,)

In [38]:
df['feature1'].value_counts()

1    313
0     38
Name: feature1, dtype: int64

In [39]:
df['feature2'].value_counts()

0    351
Name: feature2, dtype: int64

In [40]:
train_data.drop('feature2', inplace=True, axis=1)

In [41]:
test_data.drop('feature2', inplace=True, axis=1)

In [42]:
mean = train_data.mean()
std = train_data.std()

train_data-=mean
train_data/=std

test_data-=mean
test_data/=std

In [43]:
train_data.head()

   feature1  feature3  feature4  ...  feature32  feature33  feature34
0   0.34987 -0.053380 -1.604843  ...  -0.024131  -0.274176  -0.939204
1   0.34987  0.709192  0.085723  ...   0.925333   0.402143   1.023906
2   0.34987  0.709192  0.011267  ...   1.419360  -0.456947   1.459514
3   0.34987  0.226956 -0.114155  ...   0.048216   0.577280  -0.023241
4   0.34987 -1.316890 -1.290805  ...   0.019639  -0.584006  -0.055582

[5 rows x 33 columns]

In [44]:
test_data.head()

     feature1  feature3  feature4  ...  feature32  feature33  feature34
210   0.34987  0.709192  2.163699  ...   0.024376  -0.261215   1.636506
211   0.34987  0.130464 -0.199067  ...  -1.662498  -1.005462  -2.176258
212   0.34987 -0.013096 -0.106993  ...   0.019639  -0.273667   0.099588
213   0.34987  0.433065  0.305406  ...  -0.364009  -1.364025  -0.733223
214   0.34987  0.709192 -0.164199  ...   0.071690   1.233713  -0.204602

[5 rows x 33 columns]

In [45]:
pd.options.display.float_format = '{:.4f}'.format

In [46]:
train_data.mean()[0:5]

feature1    0.0000
feature3   -0.0000
feature4   -0.0000
feature5    0.0000
feature6   -0.0000
dtype: float64

In [47]:
train_data.std()[0:5]

feature1   1.0000
feature3   1.0000
feature4   1.0000
feature5   1.0000
feature6   1.0000
dtype: float64

In [48]:
train_targets = train_targets.map({'g':1, 'b':0})

In [49]:
train_targets.head()

0    0
1    1
2    1
3    1
4    0
Name: label, dtype: int64

In [50]:
test_targets = test_targets.map({'g':1, 'b':0})

In [51]:
test_targets.head()

210    1
211    0
212    1
213    1
214    1
Name: label, dtype: int64

In [52]:
from keras import models, layers, regularizers

model = models.Sequential()

model.add(layers.Dense(16, input_shape=(train_data.shape[1],), activation='relu', kernel_regularizer=regularizers.l2(0.01)))
model.add(layers.Dense(10, activation='relu', kernel_regularizer=regularizers.l2(0.01)))
model.add(layers.Dense(6, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [53]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [55]:
history = model.fit(train_data, train_targets, validation_split=0.2, epochs=100)

Epoch 1/100
6/6 [==============================] - 0s 25ms/step - loss: 0.1278 - accuracy: 1.0000 - val_loss: 0.3141 - val_accuracy: 0.9048
Epoch 2/100
6/6 [==============================] - 0s 22ms/step - loss: 0.1263 - accuracy: 1.0000 - val_loss: 0.3125 - val_accuracy: 0.9048
Epoch 3/100
6/6 [==============================] - 0s 22ms/step - loss: 0.1253 - accuracy: 1.0000 - val_loss: 0.3080 - val_accuracy: 0.9048
Epoch 4/100
6/6 [==============================] - 0s 23ms/step - loss: 0.1243 - accuracy: 1.0000 - val_loss: 0.3066 - val_accuracy: 0.9048
Epoch 5/100
6/6 [==============================] - 0s 22ms/step - loss: 0.1232 - accuracy: 1.0000 - val_loss: 0.3064 - val_accuracy: 0.9048
Epoch 6/100
6/6 [==============================] - 0s 22ms/step - loss: 0.1221 - accuracy: 1.0000 - val_loss: 0.3049 - val_accuracy: 0.9048
Epoch 7/100
6/6 [==============================] - 0s 23ms/step - loss: 0.1209 - accuracy: 1.0000 - val_loss: 0.3045 - val_accuracy: 0.9048
Epoch 8/100
6/6 [==============================] - 0s 23ms/step - loss: 0.1201 - accuracy: 1.0000 - val_loss: 0.3031 - val_accuracy: 0.9048
Epoch 9/100
6/6 [==============================] - 0s 25ms/step - loss: 0.1189 - accuracy: 1.0000 - val_loss: 0.3038 - val_accuracy: 0.9048
Epoch 10/100
6/6 [==============================] - 0s 23ms/step - loss: 0.1180 - accuracy: 1.0000 - val_loss: 0.3018 - val_accuracy: 0.9048
Epoch 11/100
6/6 [==============================] - 0s 24ms/step - loss: 0.1171 - accuracy: 1.0000 - val_loss: 0.3022 - val_accuracy: 0.9048
Epoch 12/100
6/6 [==============================] - 0s 23ms/step - loss: 0.1160 - accuracy: 1.0000 - val_loss: 0.3009 - val_accuracy: 0.9048
Epoch 13/100
6/6 [==============================] - 0s 25ms/step - loss: 0.1150 - accuracy: 1.0000 - val_loss: 0.3012 - val_accuracy: 0.9048
Epoch 14/100
6/6 [==============================] - 0s 25ms/step - loss: 0.1140 - accuracy: 1.0000 - val_loss: 0.3028 - val_accuracy: 0.9048
Epoch 15/100
6/6 [==============================] - 0s 24ms/step - loss: 0.1133 - accuracy: 1.0000 - val_loss: 0.3027 - val_accuracy: 0.9048
Epoch 16/100
6/6 [==============================] - 0s 23ms/step - loss: 0.1122 - accuracy: 1.0000 - val_loss: 0.3000 - val_accuracy: 0.9048
Epoch 17/100
6/6 [==============================] - 0s 23ms/step - loss: 0.1113 - accuracy: 1.0000 - val_loss: 0.2983 - val_accuracy: 0.9048
Epoch 18/100
6/6 [==============================] - 0s 24ms/step - loss: 0.1104 - accuracy: 1.0000 - val_loss: 0.2983 - val_accuracy: 0.9048
Epoch 19/100
6/6 [==============================] - 0s 22ms/step - loss: 0.1093 - accuracy: 1.0000 - val_loss: 0.2974 - val_accuracy: 0.9048
Epoch 20/100
6/6 [==============================] - 0s 22ms/step - loss: 0.1086 - accuracy: 1.0000 - val_loss: 0.2952 - val_accuracy: 0.9048
Epoch 21/100
6/6 [==============================] - 0s 24ms/step - loss: 0.1075 - accuracy: 1.0000 - val_loss: 0.2946 - val_accuracy: 0.9048
Epoch 22/100
6/6 [==============================] - 0s 22ms/step - loss: 0.1066 - accuracy: 1.0000 - val_loss: 0.2943 - val_accuracy: 0.9048
Epoch 23/100
6/6 [==============================] - 0s 23ms/step - loss: 0.1058 - accuracy: 1.0000 - val_loss: 0.2919 - val_accuracy: 0.9048
Epoch 24/100
6/6 [==============================] - 0s 23ms/step - loss: 0.1050 - accuracy: 1.0000 - val_loss: 0.2916 - val_accuracy: 0.9286
Epoch 25/100
6/6 [==============================] - 0s 23ms/step - loss: 0.1041 - accuracy: 1.0000 - val_loss: 0.2944 - val_accuracy: 0.9048
Epoch 26/100
6/6 [==============================] - 0s 22ms/step - loss: 0.1030 - accuracy: 1.0000 - val_loss: 0.2933 - val_accuracy: 0.9048
Epoch 27/100
6/6 [==============================] - 0s 24ms/step - loss: 0.1026 - accuracy: 1.0000 - val_loss: 0.2913 - val_accuracy: 0.9048
Epoch 28/100
6/6 [==============================] - 0s 22ms/step - loss: 0.1014 - accuracy: 1.0000 - val_loss: 0.2918 - val_accuracy: 0.9048
Epoch 29/100
6/6 [==============================] - 0s 25ms/step - loss: 0.1006 - accuracy: 1.0000 - val_loss: 0.2919 - val_accuracy: 0.9048
Epoch 30/100
6/6 [==============================] - 0s 26ms/step - loss: 0.0997 - accuracy: 1.0000 - val_loss: 0.2913 - val_accuracy: 0.9048
Epoch 31/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0990 - accuracy: 1.0000 - val_loss: 0.2893 - val_accuracy: 0.9048
Epoch 32/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0980 - accuracy: 1.0000 - val_loss: 0.2881 - val_accuracy: 0.9048
Epoch 33/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0973 - accuracy: 1.0000 - val_loss: 0.2885 - val_accuracy: 0.9286
Epoch 34/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0964 - accuracy: 1.0000 - val_loss: 0.2888 - val_accuracy: 0.9048
Epoch 35/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0958 - accuracy: 1.0000 - val_loss: 0.2881 - val_accuracy: 0.9286
Epoch 36/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0951 - accuracy: 1.0000 - val_loss: 0.2867 - val_accuracy: 0.9286
Epoch 37/100
6/6 [==============================] - 0s 24ms/step - loss: 0.0942 - accuracy: 1.0000 - val_loss: 0.2900 - val_accuracy: 0.9048
Epoch 38/100
6/6 [==============================] - 0s 25ms/step - loss: 0.0945 - accuracy: 1.0000 - val_loss: 0.2919 - val_accuracy: 0.9048
Epoch 39/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0929 - accuracy: 1.0000 - val_loss: 0.2895 - val_accuracy: 0.9048
Epoch 40/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0919 - accuracy: 1.0000 - val_loss: 0.2870 - val_accuracy: 0.9286
Epoch 41/100
6/6 [==============================] - 0s 24ms/step - loss: 0.0912 - accuracy: 1.0000 - val_loss: 0.2833 - val_accuracy: 0.9286
Epoch 42/100
6/6 [==============================] - 0s 24ms/step - loss: 0.0906 - accuracy: 1.0000 - val_loss: 0.2805 - val_accuracy: 0.9524
Epoch 43/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0900 - accuracy: 1.0000 - val_loss: 0.2787 - val_accuracy: 0.9286
Epoch 44/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0891 - accuracy: 1.0000 - val_loss: 0.2777 - val_accuracy: 0.9524
Epoch 45/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0885 - accuracy: 1.0000 - val_loss: 0.2770 - val_accuracy: 0.9524
Epoch 46/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0881 - accuracy: 1.0000 - val_loss: 0.2793 - val_accuracy: 0.9524
Epoch 47/100
6/6 [==============================] - 0s 27ms/step - loss: 0.0873 - accuracy: 1.0000 - val_loss: 0.2774 - val_accuracy: 0.9524
Epoch 48/100
6/6 [==============================] - 0s 25ms/step - loss: 0.0863 - accuracy: 1.0000 - val_loss: 0.2727 - val_accuracy: 0.9524
Epoch 49/100
6/6 [==============================] - 0s 25ms/step - loss: 0.0865 - accuracy: 1.0000 - val_loss: 0.2682 - val_accuracy: 0.9524
Epoch 50/100
6/6 [==============================] - 0s 25ms/step - loss: 0.0858 - accuracy: 1.0000 - val_loss: 0.2757 - val_accuracy: 0.9524
Epoch 51/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0860 - accuracy: 1.0000 - val_loss: 0.2765 - val_accuracy: 0.9524
Epoch 52/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0838 - accuracy: 1.0000 - val_loss: 0.2693 - val_accuracy: 0.9524
Epoch 53/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0830 - accuracy: 1.0000 - val_loss: 0.2717 - val_accuracy: 0.9286
Epoch 54/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0835 - accuracy: 1.0000 - val_loss: 0.2726 - val_accuracy: 0.9286
Epoch 55/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0821 - accuracy: 1.0000 - val_loss: 0.2720 - val_accuracy: 0.9524
Epoch 56/100
6/6 [==============================] - 0s 21ms/step - loss: 0.0810 - accuracy: 1.0000 - val_loss: 0.2707 - val_accuracy: 0.9524
Epoch 57/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0806 - accuracy: 1.0000 - val_loss: 0.2690 - val_accuracy: 0.9524
Epoch 58/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0801 - accuracy: 1.0000 - val_loss: 0.2656 - val_accuracy: 0.9524
Epoch 59/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0792 - accuracy: 1.0000 - val_loss: 0.2611 - val_accuracy: 0.9524
Epoch 60/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0787 - accuracy: 1.0000 - val_loss: 0.2597 - val_accuracy: 0.9524
Epoch 61/100
6/6 [==============================] - 0s 24ms/step - loss: 0.0781 - accuracy: 1.0000 - val_loss: 0.2590 - val_accuracy: 0.9524
Epoch 62/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0775 - accuracy: 1.0000 - val_loss: 0.2609 - val_accuracy: 0.9286
Epoch 63/100
6/6 [==============================] - 0s 26ms/step - loss: 0.0775 - accuracy: 1.0000 - val_loss: 0.2615 - val_accuracy: 0.9524
Epoch 64/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0773 - accuracy: 1.0000 - val_loss: 0.2671 - val_accuracy: 0.9524
Epoch 65/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0769 - accuracy: 1.0000 - val_loss: 0.2651 - val_accuracy: 0.9524
Epoch 66/100
6/6 [==============================] - 0s 25ms/step - loss: 0.0759 - accuracy: 1.0000 - val_loss: 0.2631 - val_accuracy: 0.9524
Epoch 67/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0752 - accuracy: 1.0000 - val_loss: 0.2632 - val_accuracy: 0.9524
Epoch 68/100
6/6 [==============================] - 0s 21ms/step - loss: 0.0749 - accuracy: 1.0000 - val_loss: 0.2626 - val_accuracy: 0.9524
Epoch 69/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0740 - accuracy: 1.0000 - val_loss: 0.2615 - val_accuracy: 0.9524
Epoch 70/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0735 - accuracy: 1.0000 - val_loss: 0.2587 - val_accuracy: 0.9524
Epoch 71/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0731 - accuracy: 1.0000 - val_loss: 0.2568 - val_accuracy: 0.9524
Epoch 72/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0724 - accuracy: 1.0000 - val_loss: 0.2560 - val_accuracy: 0.9524
Epoch 73/100
6/6 [==============================] - 0s 24ms/step - loss: 0.0721 - accuracy: 1.0000 - val_loss: 0.2552 - val_accuracy: 0.9524
Epoch 74/100
6/6 [==============================] - 0s 24ms/step - loss: 0.0716 - accuracy: 1.0000 - val_loss: 0.2537 - val_accuracy: 0.9524
Epoch 75/100
6/6 [==============================] - 0s 21ms/step - loss: 0.0711 - accuracy: 1.0000 - val_loss: 0.2524 - val_accuracy: 0.9524
Epoch 76/100
6/6 [==============================] - 0s 21ms/step - loss: 0.0706 - accuracy: 1.0000 - val_loss: 0.2522 - val_accuracy: 0.9524
Epoch 77/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0704 - accuracy: 1.0000 - val_loss: 0.2518 - val_accuracy: 0.9524
Epoch 78/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0699 - accuracy: 1.0000 - val_loss: 0.2516 - val_accuracy: 0.9524
Epoch 79/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0693 - accuracy: 1.0000 - val_loss: 0.2513 - val_accuracy: 0.9524
Epoch 80/100
6/6 [==============================] - 0s 25ms/step - loss: 0.0689 - accuracy: 1.0000 - val_loss: 0.2500 - val_accuracy: 0.9524
Epoch 81/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0686 - accuracy: 1.0000 - val_loss: 0.2499 - val_accuracy: 0.9524
Epoch 82/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0686 - accuracy: 1.0000 - val_loss: 0.2498 - val_accuracy: 0.9524
Epoch 83/100
6/6 [==============================] - 0s 24ms/step - loss: 0.0680 - accuracy: 1.0000 - val_loss: 0.2489 - val_accuracy: 0.9524
Epoch 84/100
6/6 [==============================] - 0s 24ms/step - loss: 0.0675 - accuracy: 1.0000 - val_loss: 0.2509 - val_accuracy: 0.9524
Epoch 85/100
6/6 [==============================] - 0s 27ms/step - loss: 0.0671 - accuracy: 1.0000 - val_loss: 0.2492 - val_accuracy: 0.9524
Epoch 86/100
6/6 [==============================] - 0s 24ms/step - loss: 0.0666 - accuracy: 1.0000 - val_loss: 0.2471 - val_accuracy: 0.9524
Epoch 87/100
6/6 [==============================] - 0s 25ms/step - loss: 0.0661 - accuracy: 1.0000 - val_loss: 0.2451 - val_accuracy: 0.9524
Epoch 88/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0658 - accuracy: 1.0000 - val_loss: 0.2462 - val_accuracy: 0.9524
Epoch 89/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0654 - accuracy: 1.0000 - val_loss: 0.2456 - val_accuracy: 0.9524
Epoch 90/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0650 - accuracy: 1.0000 - val_loss: 0.2468 - val_accuracy: 0.9524
Epoch 91/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0647 - accuracy: 1.0000 - val_loss: 0.2443 - val_accuracy: 0.9524
Epoch 92/100
6/6 [==============================] - 0s 20ms/step - loss: 0.0641 - accuracy: 1.0000 - val_loss: 0.2399 - val_accuracy: 0.9524
Epoch 93/100
6/6 [==============================] - 0s 24ms/step - loss: 0.0641 - accuracy: 1.0000 - val_loss: 0.2407 - val_accuracy: 0.9524
Epoch 94/100
6/6 [==============================] - 0s 26ms/step - loss: 0.0639 - accuracy: 1.0000 - val_loss: 0.2512 - val_accuracy: 0.9524
Epoch 95/100
6/6 [==============================] - 0s 23ms/step - loss: 0.0642 - accuracy: 1.0000 - val_loss: 0.2503 - val_accuracy: 0.9524
Epoch 96/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0630 - accuracy: 1.0000 - val_loss: 0.2437 - val_accuracy: 0.9524
Epoch 97/100
6/6 [==============================] - 0s 24ms/step - loss: 0.0625 - accuracy: 1.0000 - val_loss: 0.2397 - val_accuracy: 0.9524
Epoch 98/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0622 - accuracy: 1.0000 - val_loss: 0.2420 - val_accuracy: 0.9524
Epoch 99/100
6/6 [==============================] - 0s 21ms/step - loss: 0.0618 - accuracy: 1.0000 - val_loss: 0.2435 - val_accuracy: 0.9524
Epoch 100/100
6/6 [==============================] - 0s 22ms/step - loss: 0.0613 - accuracy: 1.0000 - val_loss: 0.2404 - val_accuracy: 0.9524

In [56]:
model.evaluate(test_data, test_targets)

5/5 [==============================] - 0s 2ms/step - loss: 0.1094 - accuracy: 0.9787

[0.10935534536838531, 0.978723406791687]

In [57]:
predictions = model.predict(test_data)

In [58]:
len(predictions)

141

In [59]:
import numpy as np

In [61]:
pd.DataFrame({'Actual':test_targets, 'Predicted':np.round(predictions.reshape(141,))})

     Actual  Predicted
210       1     1.0000
211       0     0.0000
212       1     0.0000
213       1     1.0000
214       1     1.0000
..      ...        ...
346       1     1.0000
347       0     0.0000
348       1     1.0000
349       0     0.0000
350       0     0.0000

[141 rows x 2 columns]